---
# tasks file for roles/deploy
- name: Persist VM-state is Started
  vagrant_check: 
    path: /home/student/cm/ansible/day-4
    state: started
  register: info
- name: Debugger
  debug: msg={{ info['vagrant_state'] }}

- name: "Tomcat: Deploy a War"
  deploy_module:
    url: "http://{{ info['ip_addr'] }}" 
    war: '{{ e_war }}'
    username: tomcat
    password: tomcat
    ipcheck: "{{ info['ip_addr'] }}"
  when: info['vagrant_state'] == "running"

- name: Transfer info-file
  shell: "scp -i {{ info['path_to_sshkey'] }} deploy-info.txt {{ info['username_toconnect'] }}@{{ info['ip_addr'] }}:/var/lib/tomcat/webapps"
 