---
# tasks file for roles/deploy
- name: "Tomcat: Deploy a War"
  deploy_module:
    url: "http://{{ info['ip_addr'] }}" 
    war: '{{ artefact }}'
    username: tomcat
    password: tomcat
    ipcheck: "{{ info['ip_addr'] }}"
  when: info['vagrant_state'] == "running"

- name: Transfer info-file
  shell: "scp -i {{ info['path_to_sshkey'] }} deploy-info.txt {{ info['username_toconnect'] }}@{{ info['ip_addr'] }}:/var/lib/tomcat/webapps"
 