- name: Check access play
  hosts: localhost
  
  tasks:
    - name: Availability Check
      uri:
        url: "http://{{ tomcat_ip }}/{{ war_name }}"
        status_code: 200

- name: Web Service Testing
  hosts: vagrant
  roles:
    - role: nginx_test
    - role: java_test
    - role: tomcat_test