- name: "No need to Check if VM is not running..."
  hosts: localhost
- include: createvm.yml

- name: Check access play
  hosts: localhost

  vars:
    artefact: "./some-war-app-42.war"
    war_name: "{{ artefact | basename }}"
  
  tasks:
    - name: Availability Check
      uri:
        url: "http://{{ info['ip_addr'] }}/{{ war_name }}"
        status_code: 200

- name: Web Service Testing
  hosts: vagrant
  roles:
    - role: nginx_test
    - role: java_test
    - role: tomcat_test