- name: "Starting VM --> Adding hosts"
  hosts: localhost

  tasks:

  - name: Persist VM-state is Started
    vagrant_check: 
      path: ./Vagrantfile
      state: started
    register: info
  - name: Debugger
    debug: msg={{ info['vagrant_state'] }}




