- name: Create VM
  hosts: localhost
- include: createvm.yml


- name: "Deploy War to Tomcat"
  hosts: localhost
  vars:  
    artefact: "./target/mnt-exam.war"

  tasks:

  - name: "Tomcat: Deploy a War"
    deploy_module:
      url: "http://{{ info['ip_addr'] }}" 
      war: '{{ artefact }}'
      username: tomcat
      password: tomcat
    when: info['vagrant_state'] == "running"

  - name: Debug
    debug: msg={{ info['vagrant_state'] }}

- name: Deploy info Play
  hosts: vagrant
  tasks:
  - name: Transfer info-file
    copy: 
      src: ./deploy-info.txt
      dest: /var/lib/tomcat/webapps
