- name: Create VM
  include_playbook: createvm.yml

- name: Provision VM
  include_playbook: provisionvm.yml

- name: "Deploy War to Tomcat"
  hosts: localhost
  roles:
  - role: deploy
  vars:
    e_war: "./target/mnt-exam.war"