- name: Provision VM
  hosts: localhost
- include: createvm.yml
- include: provisionvm.yml

- name: "Deploy War to Tomcat"
  hosts: localhost
  roles:
  - role: deploy
    vars:
      artefact: "./target/mnt-exam.war"